/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalonPortalRouteImport } from './routes/salon-portal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as SalonPortalIndexRouteImport } from './routes/salon-portal.index'
import { Route as SuperadminSubscriptionsRouteImport } from './routes/superadmin.subscriptions'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminSalonsRouteImport } from './routes/superadmin.salons'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as SalonPortalInboxRouteImport } from './routes/salon-portal.inbox'
import { Route as SalonPortalEscalationsRouteImport } from './routes/salon-portal.escalations'
import { Route as SalonPortalBusinessRouteImport } from './routes/salon-portal.business'
import { Route as SalonPortalAiRulesRouteImport } from './routes/salon-portal.ai-rules'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonPortalRoute = SalonPortalRouteImport.update({
  id: '/salon-portal',
  path: '/salon-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SalonPortalIndexRoute = SalonPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonPortalRoute,
} as any)
const SuperadminSubscriptionsRoute = SuperadminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSalonsRoute = SuperadminSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRoute,
} as any)
const SalonPortalInboxRoute = SalonPortalInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => SalonPortalRoute,
} as any)
const SalonPortalEscalationsRoute = SalonPortalEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => SalonPortalRoute,
} as any)
const SalonPortalBusinessRoute = SalonPortalBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => SalonPortalRoute,
} as any)
const SalonPortalAiRulesRoute = SalonPortalAiRulesRouteImport.update({
  id: '/ai-rules',
  path: '/ai-rules',
  getParentRoute: () => SalonPortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/salon-portal': typeof SalonPortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/salon-portal/ai-rules': typeof SalonPortalAiRulesRoute
  '/salon-portal/business': typeof SalonPortalBusinessRoute
  '/salon-portal/escalations': typeof SalonPortalEscalationsRoute
  '/salon-portal/inbox': typeof SalonPortalInboxRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/salons': typeof SuperadminSalonsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/salon-portal/': typeof SalonPortalIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/salon-portal/ai-rules': typeof SalonPortalAiRulesRoute
  '/salon-portal/business': typeof SalonPortalBusinessRoute
  '/salon-portal/escalations': typeof SalonPortalEscalationsRoute
  '/salon-portal/inbox': typeof SalonPortalInboxRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/salons': typeof SuperadminSalonsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/salon-portal': typeof SalonPortalIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/salon-portal': typeof SalonPortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/salon-portal/ai-rules': typeof SalonPortalAiRulesRoute
  '/salon-portal/business': typeof SalonPortalBusinessRoute
  '/salon-portal/escalations': typeof SalonPortalEscalationsRoute
  '/salon-portal/inbox': typeof SalonPortalInboxRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/salons': typeof SuperadminSalonsRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/subscriptions': typeof SuperadminSubscriptionsRoute
  '/salon-portal/': typeof SalonPortalIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/salon-portal'
    | '/sitemap.xml'
    | '/superadmin'
    | '/salon-portal/ai-rules'
    | '/salon-portal/business'
    | '/salon-portal/escalations'
    | '/salon-portal/inbox'
    | '/superadmin/login'
    | '/superadmin/salons'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/salon-portal/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/sitemap.xml'
    | '/salon-portal/ai-rules'
    | '/salon-portal/business'
    | '/salon-portal/escalations'
    | '/salon-portal/inbox'
    | '/superadmin/login'
    | '/superadmin/salons'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/salon-portal'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/salon-portal'
    | '/sitemap.xml'
    | '/superadmin'
    | '/salon-portal/ai-rules'
    | '/salon-portal/business'
    | '/salon-portal/escalations'
    | '/salon-portal/inbox'
    | '/superadmin/login'
    | '/superadmin/salons'
    | '/superadmin/settings'
    | '/superadmin/subscriptions'
    | '/salon-portal/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SalonPortalRoute: typeof SalonPortalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-portal': {
      id: '/salon-portal'
      path: '/salon-portal'
      fullPath: '/salon-portal'
      preLoaderRoute: typeof SalonPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/salon-portal/': {
      id: '/salon-portal/'
      path: '/'
      fullPath: '/salon-portal/'
      preLoaderRoute: typeof SalonPortalIndexRouteImport
      parentRoute: typeof SalonPortalRoute
    }
    '/superadmin/subscriptions': {
      id: '/superadmin/subscriptions'
      path: '/subscriptions'
      fullPath: '/superadmin/subscriptions'
      preLoaderRoute: typeof SuperadminSubscriptionsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/salons': {
      id: '/superadmin/salons'
      path: '/salons'
      fullPath: '/superadmin/salons'
      preLoaderRoute: typeof SuperadminSalonsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/salon-portal/inbox': {
      id: '/salon-portal/inbox'
      path: '/inbox'
      fullPath: '/salon-portal/inbox'
      preLoaderRoute: typeof SalonPortalInboxRouteImport
      parentRoute: typeof SalonPortalRoute
    }
    '/salon-portal/escalations': {
      id: '/salon-portal/escalations'
      path: '/escalations'
      fullPath: '/salon-portal/escalations'
      preLoaderRoute: typeof SalonPortalEscalationsRouteImport
      parentRoute: typeof SalonPortalRoute
    }
    '/salon-portal/business': {
      id: '/salon-portal/business'
      path: '/business'
      fullPath: '/salon-portal/business'
      preLoaderRoute: typeof SalonPortalBusinessRouteImport
      parentRoute: typeof SalonPortalRoute
    }
    '/salon-portal/ai-rules': {
      id: '/salon-portal/ai-rules'
      path: '/ai-rules'
      fullPath: '/salon-portal/ai-rules'
      preLoaderRoute: typeof SalonPortalAiRulesRouteImport
      parentRoute: typeof SalonPortalRoute
    }
  }
}

interface SalonPortalRouteChildren {
  SalonPortalAiRulesRoute: typeof SalonPortalAiRulesRoute
  SalonPortalBusinessRoute: typeof SalonPortalBusinessRoute
  SalonPortalEscalationsRoute: typeof SalonPortalEscalationsRoute
  SalonPortalInboxRoute: typeof SalonPortalInboxRoute
  SalonPortalIndexRoute: typeof SalonPortalIndexRoute
}

const SalonPortalRouteChildren: SalonPortalRouteChildren = {
  SalonPortalAiRulesRoute: SalonPortalAiRulesRoute,
  SalonPortalBusinessRoute: SalonPortalBusinessRoute,
  SalonPortalEscalationsRoute: SalonPortalEscalationsRoute,
  SalonPortalInboxRoute: SalonPortalInboxRoute,
  SalonPortalIndexRoute: SalonPortalIndexRoute,
}

const SalonPortalRouteWithChildren = SalonPortalRoute._addFileChildren(
  SalonPortalRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminSalonsRoute: typeof SuperadminSalonsRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminSubscriptionsRoute: typeof SuperadminSubscriptionsRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminSalonsRoute: SuperadminSalonsRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminSubscriptionsRoute: SuperadminSubscriptionsRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SalonPortalRoute: SalonPortalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
